# Site settings
title:          YGLENA
description:    "Testing"
baseurl:        ""
url:            "https://yglena.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         YGLENA
  twitter:      YGLENA

# Build settings
markdown:       kramdown
include:
  - _pages

# footnote setting change
#kramdown:
#  input: GFM
#  footnotes_backlink: '&#8593;&#65038;'
#  footnotes_nr: 5

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         yglena
